### ISSUE TITLE
alvar comments - historical production

### ISSUE THREAD

**Issue by alvizek** [FlowWest/urban-water-drought-data#8]
- [x] In the metadata, "quantity acre feet" says: This is a calculated value that converts the quantity to acre feet. My question is "which quantity"? Explain

**Comment by zoekanavas** [comment]
The "quantity" refers to water or delivered. The quantity can be reported to the eAR in many different units. Along with the quantity, the reporter must report the unit of measure of that quantity; this could include acre-feet (AF), centum cubic feet (CCF), gallons (G), etc. That quantity (regardless of the unit) is converted to AF; this is the value reported in this dataset.
